python3 evaluate_ensemble.py \
--algorithm astar-near \
--exp_name crim13 \
--trial 1 \
--train_data data/crim13_processed/train_crim13_data.npy \
--valid_data data/crim13_processed/val_crim13_data.npy \
--test_data data/crim13_processed/test_crim13_data.npy \
--train_labels data/crim13_processed/train_crim13_labels_other.npy \
--valid_labels data/crim13_processed/val_crim13_labels_other.npy \
--test_labels data/crim13_processed/test_crim13_labels_other.npy \
--input_type "list" \
--output_type "list" \
--input_size 19 \
--output_size 2 \
--num_labels 1 \
--lossfxn "crossentropy" \
--max_depth 3 \
--frontier_capacity 8 \
--learning_rate 0.001 \
--neural_epochs 6 \
--symbolic_epochs 15 \
--class_weights "1.0,1.0"

python3 propel.py \
--algorithm astar-near \
--exp_name example \
--trial 1 \
--train_data data/example/train_ex_data.npy \
--test_data data/example/test_ex_data.npy \
--train_labels data/example/train_ex_labels.npy \
--test_labels data/example/test_ex_labels.npy \
--input_type "list" \
--output_type "list" \
--input_size 12 \
--output_size 4 \
--num_labels 4 \
--lossfxn "crossentropy" \
--normalize \
--max_depth 2 \
--frontier_capacity 5